from data_catalog.client.asset.models.location import Location as ClientLocation


class Location (ClientLocation):
    """
    A service level class to extend the Location class generated by OpenAPI.
    """

    def __init__(self, type=None, parameters=None):
        """
        Constructor for Location
        :param str type:
        :param Parameter parameters: key value pairs describing parameters
        """
        super().__init__(type=type, parameters=parameters)

    def get_parameter(self, key):
        """
        Returns the value for a parameter key
        :param str key:
        :return: str value
        """
        if self.parameters is None:
            return None

        values = [parameter.value for parameter in self.parameters if parameter.key == key]

        return values[0] if len(values) > 0 else None
