# coding: utf-8

"""
    Data Catalog

    Data Catalog API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilard.tumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "data_catalog.client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Data Catalog",
    author="Tumó Szilárd Zsolt",
    author_email="szilard.tumo@stud.ubbcluj.ro",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Data Catalog"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Data Catalog API.  # noqa: E501
    """
)
