# coding: utf-8

"""
    Data Catalog

    Data Catalog API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilard.tumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "data_catalog"
VERSION = "1.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "pandas~=1.1.3",
    "six~=1.15.0",
    "certifi~=2020.6.20",
    "urllib3~=1.25.11",
    "python-dateutil~=2.8.1",
    "azure-storage-blob~=12.6.0",
    "PyYAML~=5.3.1"
]

setup(
    name=NAME,
    version=VERSION,
    description="Data Catalog",
    author="Tumó Szilárd Zsolt",
    author_email="szilard.tumo@stud.ubbcluj.ro",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Data Catalog"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["tests"]),
    include_package_data=True,
    long_description="Data Catalog Python Client"
)
