# coding: utf-8

"""
    Data Catalog Asset Service API

    The asset handling service of the Data Catalog application.  Provides API endpoints to create, delete, and modify assets. It also manages the access rights to the assets, as private assets are only available to users that are members of it.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilard.tumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from data_catalog.client.asset.configuration import Configuration


class AssetResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'owner_id': 'str',
        'name': 'str',
        'description': 'str',
        'short_description': 'str',
        'location': 'LocationResponse',
        'tags': 'list[str]',
        'format': 'str',
        'is_public': 'bool',
        'members': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'owner_id': 'ownerId',
        'name': 'name',
        'description': 'description',
        'short_description': 'shortDescription',
        'location': 'location',
        'tags': 'tags',
        'format': 'format',
        'is_public': 'isPublic',
        'members': 'members'
    }

    def __init__(self, id=None, created_at=None, updated_at=None, owner_id=None, name=None, description=None, short_description=None, location=None, tags=None, format=None, is_public=None, members=None, local_vars_configuration=None):  # noqa: E501
        """AssetResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._created_at = None
        self._updated_at = None
        self._owner_id = None
        self._name = None
        self._description = None
        self._short_description = None
        self._location = None
        self._tags = None
        self._format = None
        self._is_public = None
        self._members = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if owner_id is not None:
            self.owner_id = owner_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if short_description is not None:
            self.short_description = short_description
        if location is not None:
            self.location = location
        if tags is not None:
            self.tags = tags
        if format is not None:
            self.format = format
        if is_public is not None:
            self.is_public = is_public
        if members is not None:
            self.members = members

    @property
    def id(self):
        """Gets the id of this AssetResponse.  # noqa: E501

        The ID of the asset.  # noqa: E501

        :return: The id of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssetResponse.

        The ID of the asset.  # noqa: E501

        :param id: The id of this AssetResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this AssetResponse.  # noqa: E501

        Date of creation.  # noqa: E501

        :return: The created_at of this AssetResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AssetResponse.

        Date of creation.  # noqa: E501

        :param created_at: The created_at of this AssetResponse.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AssetResponse.  # noqa: E501

        Date of the last update.  # noqa: E501

        :return: The updated_at of this AssetResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AssetResponse.

        Date of the last update.  # noqa: E501

        :param updated_at: The updated_at of this AssetResponse.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def owner_id(self):
        """Gets the owner_id of this AssetResponse.  # noqa: E501

        The ID of the user who owns the asset.  # noqa: E501

        :return: The owner_id of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this AssetResponse.

        The ID of the user who owns the asset.  # noqa: E501

        :param owner_id: The owner_id of this AssetResponse.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    @property
    def name(self):
        """Gets the name of this AssetResponse.  # noqa: E501

        A name of the asset.  # noqa: E501

        :return: The name of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AssetResponse.

        A name of the asset.  # noqa: E501

        :param name: The name of this AssetResponse.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 120):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `120`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 3):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `3`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this AssetResponse.  # noqa: E501

        A longer description about the content of the asset. Supports rich text formatting.  # noqa: E501

        :return: The description of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AssetResponse.

        A longer description about the content of the asset. Supports rich text formatting.  # noqa: E501

        :param description: The description of this AssetResponse.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) < 3):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `3`")  # noqa: E501

        self._description = description

    @property
    def short_description(self):
        """Gets the short_description of this AssetResponse.  # noqa: E501

        Short description breifly defining the contents of the asset.  # noqa: E501

        :return: The short_description of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """Sets the short_description of this AssetResponse.

        Short description breifly defining the contents of the asset.  # noqa: E501

        :param short_description: The short_description of this AssetResponse.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                short_description is not None and len(short_description) > 300):
            raise ValueError("Invalid value for `short_description`, length must be less than or equal to `300`")  # noqa: E501

        self._short_description = short_description

    @property
    def location(self):
        """Gets the location of this AssetResponse.  # noqa: E501


        :return: The location of this AssetResponse.  # noqa: E501
        :rtype: LocationResponse
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this AssetResponse.


        :param location: The location of this AssetResponse.  # noqa: E501
        :type: LocationResponse
        """

        self._location = location

    @property
    def tags(self):
        """Gets the tags of this AssetResponse.  # noqa: E501

        A list of keywords assigned to the asset.  # noqa: E501

        :return: The tags of this AssetResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AssetResponse.

        A list of keywords assigned to the asset.  # noqa: E501

        :param tags: The tags of this AssetResponse.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def format(self):
        """Gets the format of this AssetResponse.  # noqa: E501

        The file format of the asset.  # noqa: E501

        :return: The format of this AssetResponse.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this AssetResponse.

        The file format of the asset.  # noqa: E501

        :param format: The format of this AssetResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["csv", "json"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and format not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `format` ({0}), must be one of {1}"  # noqa: E501
                .format(format, allowed_values)
            )

        self._format = format

    @property
    def is_public(self):
        """Gets the is_public of this AssetResponse.  # noqa: E501

        Whether the asset is accessible by anyone or not.  # noqa: E501

        :return: The is_public of this AssetResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this AssetResponse.

        Whether the asset is accessible by anyone or not.  # noqa: E501

        :param is_public: The is_public of this AssetResponse.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    @property
    def members(self):
        """Gets the members of this AssetResponse.  # noqa: E501

        The IDs of the users which the asset is accessible for.  # noqa: E501

        :return: The members of this AssetResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this AssetResponse.

        The IDs of the users which the asset is accessible for.  # noqa: E501

        :param members: The members of this AssetResponse.  # noqa: E501
        :type: list[str]
        """

        self._members = members

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssetResponse):
            return True

        return self.to_dict() != other.to_dict()
