# coding: utf-8

"""
    Data Catalog User Service API

    The user handling service of the Data Catalog application.  Provides API endpoints to register, and log in to the application.  It communicates with other services to tell informations about tokens, thus authorizing a request made at another service. Provides endpoints to delete, and list users for administrative purposes.  The api supports JWT token, and API key authentication.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilard.tumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from data_catalog.client.user.configuration import Configuration


class TokenInfoRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'token': 'str',
        'token_type_hint': 'str'
    }

    attribute_map = {
        'token': 'token',
        'token_type_hint': 'token_type_hint'
    }

    def __init__(self, token=None, token_type_hint=None, local_vars_configuration=None):  # noqa: E501
        """TokenInfoRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._token = None
        self._token_type_hint = None
        self.discriminator = None

        self.token = token
        if token_type_hint is not None:
            self.token_type_hint = token_type_hint

    @property
    def token(self):
        """Gets the token of this TokenInfoRequest.  # noqa: E501

        The string value of the token.  # noqa: E501

        :return: The token of this TokenInfoRequest.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenInfoRequest.

        The string value of the token.  # noqa: E501

        :param token: The token of this TokenInfoRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and token is None:  # noqa: E501
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def token_type_hint(self):
        """Gets the token_type_hint of this TokenInfoRequest.  # noqa: E501

        A hint about the type of the token submitted for introspection.  # noqa: E501

        :return: The token_type_hint of this TokenInfoRequest.  # noqa: E501
        :rtype: str
        """
        return self._token_type_hint

    @token_type_hint.setter
    def token_type_hint(self, token_type_hint):
        """Sets the token_type_hint of this TokenInfoRequest.

        A hint about the type of the token submitted for introspection.  # noqa: E501

        :param token_type_hint: The token_type_hint of this TokenInfoRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["access_token", "api_key"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and token_type_hint not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `token_type_hint` ({0}), must be one of {1}"  # noqa: E501
                .format(token_type_hint, allowed_values)
            )

        self._token_type_hint = token_type_hint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenInfoRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenInfoRequest):
            return True

        return self.to_dict() != other.to_dict()
