# coding: utf-8

"""
    User

    Data Catalog User API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: katacseke@gmail.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from data_catalog.client.user.configuration import Configuration


class UserLoginResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'token': 'str',
        'user': 'UserResponse'
    }

    attribute_map = {
        'token': 'token',
        'user': 'user'
    }

    def __init__(self, token=None, user=None, local_vars_configuration=None):  # noqa: E501
        """UserLoginResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._token = None
        self._user = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if user is not None:
            self.user = user

    @property
    def token(self):
        """Gets the token of this UserLoginResponse.  # noqa: E501

        JWT token sent by the server. The client will send this with every request to authenticate themselves.  # noqa: E501

        :return: The token of this UserLoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this UserLoginResponse.

        JWT token sent by the server. The client will send this with every request to authenticate themselves.  # noqa: E501

        :param token: The token of this UserLoginResponse.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def user(self):
        """Gets the user of this UserLoginResponse.  # noqa: E501


        :return: The user of this UserLoginResponse.  # noqa: E501
        :rtype: UserResponse
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserLoginResponse.


        :param user: The user of this UserLoginResponse.  # noqa: E501
        :type: UserResponse
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLoginResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLoginResponse):
            return True

        return self.to_dict() != other.to_dict()
