# coding: utf-8

# flake8: noqa

"""
    Data Catalog User Service API

    The user handling service of the Data Catalog application.  Provides API endpoints to register, and log in to the application.  It communicates with other services to tell informations about tokens, thus authorizing a request made at another service. Provides endpoints to delete, and list users for administrative purposes.  The api supports JWT token, and API key authentication.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilard.tumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from data_catalog.client.user.api.api_key_api import ApiKeyApi
from data_catalog.client.user.api.authentication_api import AuthenticationApi
from data_catalog.client.user.api.user_api import UserApi

# import ApiClient
from data_catalog.client.user.api_client import ApiClient
from data_catalog.client.user.configuration import Configuration
from data_catalog.client.user.exceptions import OpenApiException
from data_catalog.client.user.exceptions import ApiTypeError
from data_catalog.client.user.exceptions import ApiValueError
from data_catalog.client.user.exceptions import ApiKeyError
from data_catalog.client.user.exceptions import ApiException
# import models into sdk package
from data_catalog.client.user.models.api_key_creation_request import ApiKeyCreationRequest
from data_catalog.client.user.models.api_key_creation_response import ApiKeyCreationResponse
from data_catalog.client.user.models.api_key_response import ApiKeyResponse
from data_catalog.client.user.models.error_response import ErrorResponse
from data_catalog.client.user.models.token_info_request import TokenInfoRequest
from data_catalog.client.user.models.token_info_response import TokenInfoResponse
from data_catalog.client.user.models.user_creation_request import UserCreationRequest
from data_catalog.client.user.models.user_login_request import UserLoginRequest
from data_catalog.client.user.models.user_login_response import UserLoginResponse
from data_catalog.client.user.models.user_response import UserResponse
from data_catalog.client.user.models.user_role_update_request import UserRoleUpdateRequest
from data_catalog.client.user.models.user_update_request import UserUpdateRequest

