# coding: utf-8

# flake8: noqa

"""
    Data Catalog Versioning API

    This API is used to communicate with the versioning service of the Data Catalog application.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: szilardtumo@stud.ubbcluj.ro
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from data_catalog.client.versioning.api.version_api import VersionApi

# import ApiClient
from data_catalog.client.versioning.api_client import ApiClient
from data_catalog.client.versioning.configuration import Configuration
from data_catalog.client.versioning.exceptions import OpenApiException
from data_catalog.client.versioning.exceptions import ApiTypeError
from data_catalog.client.versioning.exceptions import ApiValueError
from data_catalog.client.versioning.exceptions import ApiKeyError
from data_catalog.client.versioning.exceptions import ApiException
# import models into sdk package
from data_catalog.client.versioning.models.content_response import ContentResponse
from data_catalog.client.versioning.models.error_response import ErrorResponse
from data_catalog.client.versioning.models.version_request import VersionRequest
from data_catalog.client.versioning.models.version_response import VersionResponse

